version: '3'

services:
  paintbot:
    # 使用官方镜像或你的镜像仓库
    image: kevinlin86/paintbot-hub:latest
    # 如果要使用本地构建，注释掉 image 行，取消注释下面的 build 行
    # build: .
    container_name: paintbot
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped